### ISSUE TITLE
Sentry reporting LaunchDarklyFlagFetchError

### ISSUE THREAD

**Issue by pratishshr** [launchdarkly/react-client-sdk#106]
**Describe the bug**
We are getting this error in Sentry currently in production. Is this any chance because of the SDK ?

![image](https://user-images.githubusercontent.com/13301510/143255646-bca18718-4809-41a8-9d66-94823b071927.png)

**To reproduce**
Not sure, it's only reported by Sentry in production app

**Expected behavior**
Should not report the error 

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
```
"launchdarkly-react-client-sdk": "^2.23.3",
```

**Language version, developer tools**

**OS/platform**
It mostly occurs in Mobile Safari and Snapchat webviews

**Additional context**

**Comment by eli-darkly** [comment]
If your question is "does the error called 'LaunchDarklyFlagFetchError' ever get logged by the LaunchDarkly SDK" then the answer is yes, that is how the SDK reports that a network request has failed.

If your question is "why did a network request fail", it's impossible to answer that question from only the information you've given here. All I can see is that it is _not_ the result of the request you showed in that screenshot, the one to `events.launchdarkly.com`, because that request is delivering diagnostic data to LaunchDarkly; "LaunchDarklyFlagFetchError", as the name implies, is only for the failure of a request to get flags from LaunchDarkly. That request would be to either `app.launchdarkly.com` or `clientsdk.launchdarkly.com`.

**Comment by eli-darkly** [comment]
Is Sentry not showing you any information about a failed HTTP request?

**Comment by pratishshr** [comment]
Ah right sorry, here are some more details about the error.

We are using NextJS. 
This is the breadcrumb shown in sentry.
![Uploading image.png…]()
![image](https://user-images.githubusercontent.com/13301510/144826469-1873da74-dfa5-4451-858d-92fd06f7c7f4.png)

**Comment by pratishshr** [comment]
Ah right, sorry.
Here's the breadcrumb of the error.

![image](https://user-images.githubusercontent.com/13301510/144826905-3508a871-664e-4a40-956d-c814c6a1ef8f.png)
![image](https://user-images.githubusercontent.com/13301510/144826924-e540c1d0-ca60-4067-bfb6-38712f90ad9b.png)

Looks like it errored out while fetching nextjs static content and data.
![image](https://user-images.githubusercontent.com/13301510/144827022-3d389201-b6d1-45fd-8536-278c72571b5d.png)


Full raw error:
```
LaunchDarklyFlagFetchError: network error (Error)
  at o(./node_modules/launchdarkly-js-client-sdk/dist/ldclient.es.js:1:1061)
  at call(./node_modules/launchdarkly-js-client-sdk/dist/ldclient.es.js:1:1324)
  at __webpack_require__(webpack://_N_E/webpack/bootstrap:21:33)
  at call(./node_modules/launchdarkly-react-client-sdk/lib/initLDClient.js:50:36)
  at __webpack_require__(webpack://_N_E/webpack/bootstrap:21:33)
  at call(./node_modules/launchdarkly-react-client-sdk/lib/provider.js:88:38)
  at __webpack_require__(webpack://_N_E/webpack/bootstrap:21:33)
  at call(./node_modules/launchdarkly-react-client-sdk/lib/index.js:7:34)
  at __webpack_require__(webpack://_N_E/webpack/bootstrap:21:33)
  at call(chunks/pages/_app-4b5e9a9166ccb2649421.js:17:30)
  at __webpack_require__(webpack://_N_E/webpack/bootstrap:21:33)
  at ? (chunks/pages/_app-4b5e9a9166ccb2649421.js:5:16)
  at promiseReactionJob([native code])
  ```
  
  Also, it seems to only happen with Safari on iPhone and Snapchat webview.
  
![image](https://user-images.githubusercontent.com/13301510/144827218-283e870f-95ee-471a-8cc0-03a7e9a0d18f.png)

**Comment by francescov1** [comment]
+1

**Comment by grgilad** [comment]
Can see this on a multi-day basis:
LaunchDarklyFlagFetchError: network error (Error)
  at ? (../../node_modules/launchdarkly-js-sdk-common/dist/ldclient-common.es.js:1:16981)

**Comment by joshketellapper** [comment]
+1 see this too

**Comment by eli-darkly** [comment]
Well, again, this is an extremely general kind of error report. It is expected and correct for the SDK to log that there was a network error, if in fact there was a network error. I have no way to know whether the actual cause is the same or different for the several users who have commented here. The Sentry information posted by @pratishsr earlier does seem to indicate that there was some kind of I/O error (that is, "Encountered an unexpected network error from axios: Network error" does not seem to be just a duplicate of the message from the LaunchDarkly SDK) but unfortunately it's not providing any other details.

**Comment by louis-launchdarkly** [comment]
Hello @francescov1, @grgilad, and @joshketellapper, thank you for reaching out on this issue too. Do you have any further information like stack track, what kind of environment and browser your app runs in, time and frequency that the error occurs, React SDK version?

We will need more information to help narrow down what's going on so I appreciate any input.

**Comment by grgilad** [comment]
Here's an example:
GET https://app.launchdarkly.com/sdk/evalx/602488fac930a30b0067eaeb/users/eyJhbm9ueW1vdXMiOnRydWUsImtleSI6IjRiOWYwMDUxLTZjZDgtMTFlYy04M2RjLTVmNDcwZDJjYjU3MSJ9

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

launchdarkly-react-client-sdk - 2.23.3

**Comment by eli-darkly** [comment]
@grgilad That is a valid URL and I have no problem accessing it with any client. It's hard to think of any way that the SDK itself could cause "network error" to be logged unless there was in fact a network error (or something else interfering with the browser in a way that manifests as a network error). The SDK does pretty ordinary HTTP requests. Do you have reason to believe that it's _only_ the LaunchDarkly SDK that is having problems like this in your environment?

**Comment by francescov1** [comment]
@louis-launchdarkly 

We haven't had any other network errors reported other than from LD. Additionally, this seems to be occurring almost solely in Snapchat webviews, with a few events in mobile safari as well. Error info looks pretty much the same as @pratishshr.

We've got a reported `code` field that is undefined; is that normal? Would be nice to have some way to determine if it was just a transient network error or anything else.  
<img width="630" alt="Screen Shot 2022-01-09 at 9 37 22 AM" src="https://user-images.githubusercontent.com/26126685/148686965-7e8706a4-ee0a-49b7-ab56-d2052552680b.png">

If this is just a regular network failure (or anything else), is there any extra handling we need to do? If the SDK auto-retries in this case then it seems pointless to report or pay attention to these errors, otherwise we should probably implement our own retry strategy.

**Comment by yufio** [comment]
@francescov1 did you manage to find the reason behind this?
We have used LD for more than a year and recently (~ 1-1.5 months ago) started seeing this error relatively often.
We've got the same response from LD that it is possible to get this error but we also struggle to understand how this can happen since there's no indication that other requests fail.
I am wondering if it is related to people using ad blockers maybe 🤔

**Comment by francescov1** [comment]
@yufio Unfortunately not, still seeing it occur. I could see it being an ad blocker issue.

**Comment by immutable-pro** [comment]
Greetings! I can confirm that in [Rapid Studio](https://rapidapi.com/studio), we keep seeing this in Safari and all iOS browsers (Safari based).

**Comment by scaniflubacher** [comment]
+1 -- we're seeing this as well.
Seems to be macOS and iOS clients only.
Happy to provide any supporting information that may be helpful.

**Comment by patt-prabha** [comment]
+1  We are also seeing the same errors in huge numbers.

**Comment by Twipped** [comment]
We recently started seeing this issue, and I believe it is caused by the use of a synchronous xhr request [on page close](https://github.com/launchdarkly/js-client-sdk/blob/main/src/httpRequest.js#L35). The use of synchronous requests is deprecated by many browsers [1](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open), and Webkit explicitly disallows sync XHR on page dismissal [2](https://chromestatus.com/feature/4664843055398912).

This code should be changed to use the [`navigator.sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) API to dispatch these page close events.

**Comment by slgriffiths** [comment]
+1 Also seeing it frequently since migrating to Next.js.

**Comment by NateDawg90** [comment]
+1 Any update on this? We will likely not be able to use a client side Launch Darkly implementation until this issue is resolved.

**Comment by wilbertopachecob** [comment]
I'm also seeing this error in my next js app but only when this one runs in an iframe

**Comment by Netacci** [comment]
Fixed this issue to stop reporting to sentry by adding a catch block to my launchdarkly initialization 
     `  ldClient
             .identify({
             key: key,
             name: username,
        })
        .catch((error) => {
          console.error('Caught Error:', error.message);
        }); `

**Comment by OptoGreg** [comment]
We'd like to have the event tracking, but not get sentry flooded with messages when network errors occur.

**Comment by joker23** [comment]
Hi,

We've moved active development of the React SDK to the LaunchDarkly js-core monorepo. The successor package is `@launchdarkly/react-sdk` (v4, released 2026-04-30):

https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react

New issues, including feature requests, should be filed against the js-core repo:

https://github.com/launchdarkly/js-core/issues/new/choose

I'm closing this issue as part of a sweep of older reports. If your problem reproduces on `@launchdarkly/react-sdk` v4, please open a new issue against js-core and link back to this one -- we'll pick it up there. Thanks!
